CommandSet RohanArmoryCommandSetEdoras
	1 = Command_PurchaseTechnologyRohanBasicTraining
	2 = Command_PurchaseTechnologyRohanHeavyArmor
	3 = Command_PurchaseTechnologyRohanForgedBlades
	4	= Command_ConstructGondorTrebuchet
	5	= Command_PurchaseTechnologyGondorFireStones
	6 = Command_Sell
End
ModifierList YourTimeIsOverModifier
	Category = SPELL
	Modifier = DAMAGE_MULT 200%
	Modifier = ARMOR 50%
	ReplaceInCategoryIfLongest	= Yes
	IgnoreIfAnticategoryActive	= Yes
End

PlayerTemplate FactionCivilian
	IntrinsicSciencesMP 		= SCIENCE_MEN
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSetMP	= MenSpellStoreCommandSet
End

Object RohanArmory
	CommandSet =  RohanArmoryCommandSetEdoras
End
Object GoodSpellBook
AddModule
	Behavior = ProductionSpeedBonus ModuleTag_RohanCalltheHorde ;,;
		SpecialPowerTemplate	= SpellBookCalltheHorde
		NumberOfFrames			= 180
		SpeedMulitplier			= 20.0
		Type					= RohanArcherHorde RohanRohirrimHorde RohanRohirrimArcherHorde RohanSpearmenHorde RohanPeasantHorde GondorTrebuchet
		AvailableAtStart		= No
		RequirementsFilterMPSkirmish = SPELL_BOOK_REQUIREMENTS_FILTER
		RequirementsFilterStrategic = SPELL_BOOK_REQUIREMENTS_FILTER_STRATEGIC
	End
End
End

Object RohanTheoden
RemoveModule ModuleTag_GloriousChargeAutoAbility
RemoveModule ModuleTag_KingsFavorAutoAbility
AddModule
	Behavior = AutoAbilityBehavior ModuleTag_GloriousChargeAutoAbilityAC
		SpecialAbility	= SpecialAbilityTheodenGloriousCharge
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange	= 150 
		StartsActive = Yes
		;Query		= 20 ANY +CAVALRY -MordorBlackRiderHorde -MordorBlackRider -GondorKnightsofDolHorde -GondorKnightsofDol -WildBabyDrakeHorde -WildBabyDrake ALLIES
		Query		= 20 ANY ENEMIES +INFANTRY +CAVALRY +ARCHER +MONSTER +HERO -IMMOBILE ;+CAVALRY -MordorBlackRiderHorde -MordorBlackRider -GondorKnightsofDolHorde -GondorKnightsofDol -WildBabyDrakeHorde -WildBabyDrake ALLIES
	End
	Behavior = AutoAbilityBehavior ModuleTag_KingsFavorAutoAbilityAC
		SpecialAbility	= SpecialAbilityKingsFavor
		MaxScanRange	= 200 
		StartsActive = Yes
		Query		= 50 ANY +CAVALRY +INFANTRY -STRUCTURE -CASTLE_KEEP -BASE_FOUNDATION -HERO -MOVE_ONLY -DOZER -SUMMONED ALLIES
	End
End
End

Object RohanEowyn
RemoveModule ModuleTag_SmiteAutoAbility
RemoveModule ModuleTag_AutoAbilityShieldMaiden
AddModule
	Behavior = AutoAbilityBehavior ModuleTag_SmiteAutoAbilityAC
		SpecialAbility				= SpecialAbilitySmite
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange				= 275
		StartsActive = Yes
		Query						= 1 ANY ENEMIES +MordorFellBeast +MordorWitchKingOnFellBeast +GondorGwaihir +GondorGwaihir_Summoned +ElvenFortressEagle +KhamulFellBeast +MorgomirFellBeast +Drogoth
		Query						= 1 ANY ENEMIES +MONSTER +HERO +AngmarThrallMaster +AngmarThrallMasterInn +AngmarThrallMasterBanner +AngmarThrallMasterSpearmenBanner +AngmarThrallMasterAxeBanner +AngmarThrallMasterSlingerBanner +AngmarThrallMasterOrcBanner +AngmarThrallMasterWolfBanner +AngmarThrallMasterHillmenBanner -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE ;,; Added +AngmarThrallMaster +AngmarThrallMasterInn +AngmarThrallMasterBanner +AngmarThrallMasterSpearmenBanner +AngmarThrallMasterAxeBanner +AngmarThrallMasterSlingerBanner +AngmarThrallMasterOrcBanner +AngmarThrallMasterWolfBanner +AngmarThrallMasterHillmenBanner
	End
	Behavior = AutoAbilityBehavior ModuleTag_AutoAbilityShieldMaidenAC
		SpecialAbility				= SpecialAbilityEowynShieldMaiden
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange				= 250
		StartsActive = Yes
		Query                       = 20 ALL ENEMIES -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE 
		Query                       = 1 ANY ENEMIES +HERO +MONSTER  
	End	
End
End

Object DwarvenGimli
RemoveModule ModuleTag_GimliAxeAutoAbility
RemoveModule ModuleTag_LeapAutoAbility
RemoveModule ModuleTag_SlayerAutoAbility
AddModule
	Behavior = AutoAbilityBehavior ModuleTag_GimliAxeAutoAbilityAC 
		SpecialAbility				= SpecialAbilityGimliAxe
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange				= 250
		StartsActive = Yes
		Query = 1 ANY ENEMIES +MONSTER +HERO
		Query = 15 ALL ENEMIES -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE
	End
	Behavior = AutoAbilityBehavior ModuleTag_LeapAutoAbilityAC
		SpecialAbility	= SpecialAbilityGimliLeap
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange				= 200 ;,; 150 ;,; 135 ;100
		StartsActive = Yes
		Query						= 15 ALL ENEMIES -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE
	End
	Behavior = AutoAbilityBehavior ModuleTag_SlayerAutoAbilityAC
		SpecialAbility	= SpecialAbilityGimliHeroMode
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange				= 200 ;,; 100
		StartsActive = Yes
		Query						= 15 ALL ENEMIES -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE
		Query                       = 1 ANY ENEMIES +HERO +MONSTER
	End
End
End

Object ElvenLegolas
RemoveModule ModuleTag_HawkStrikeAutoAbility
RemoveModule ModuleTag_LightningSwordAutoAbility
AddModule
	Behavior = AutoAbilityBehavior ModuleTag_HawkStrikeAutoAbilityAC
		SpecialAbility				= SpecialAbilityHawkStrike
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange				= 400.0
		StartsActive = Yes
		Query						= 1 ANY ENEMIES +HERO +MONSTER
		Query						= 15 ALL ENEMIES -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE
	End
	Behavior = AutoAbilityBehavior ModuleTag_LightningSwordAutoAbilityAC
		SpecialAbility				= SpecialAbilityArrowStorm
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange				= 420.0
		StartsActive = Yes
		Query						= 30 ALL ENEMIES -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE
	End
End
End

Object GondorGandalf
RemoveModule ModuleTag_WizardBlastAutoAbility
; RemoveModule ModuleTag_LightningSwordAutoAbility
RemoveModule ModuleTag_SmiteAutoAbility
RemoveModule ModuleTag_WoPAutoAbility
AddModule
	Behavior = AutoAbilityBehavior ModuleTag_WizardBlastAutoAbilityAC
		SpecialAbility				= SpecialAbilityWizardBlast
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange				= GANDALF_FORCE_ATTACK_RANGE
		StartsActive = Yes
		Query						= 15 ALL ENEMIES -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE 
	End
	; Behavior = AutoAbilityBehavior ModuleTag_LightningSwordAutoAbilityAC 
		; SpecialAbility				= SpecialAbilityLightningSword
		; ForbiddenStatus = INSIDE_GARRISON 
		; MaxScanRange				= 275.0
		; StartsActive = Yes
		; Query						= 1 ANY ENEMIES +MONSTER +HERO -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE
		; Query						= 15 ALL ENEMIES -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE
	; End
	; Behavior = AutoAbilityBehavior ModuleTag_SmiteAutoAbilityAC
		; SpecialAbility				= SpecialAbilityIstariLight
		; ForbiddenStatus = INSIDE_GARRISON
		; MaxScanRange				= GANDALF_PHASER_CAST_RANGE
		; StartsActive = Yes
		; Query						= 1 ANY ENEMIES +MordorFellBeast +MordorWitchKingOnFellBeast +GondorGwaihir +GondorGwaihir_Summoned +ElvenFortressEagle +KhamulFellBeast +MorgomirFellBeast +Drogoth
		; Query						= 1 ANY ENEMIES +MONSTER +HERO -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE
	; End
	Behavior = AutoAbilityBehavior ModuleTag_WoPAutoAbilityAC
		SpecialAbility				= SpecialAbilityWordOfPower
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange				= 150
		StartsActive = Yes
		Query						= 30 ALL ENEMIES -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE 
	End
End
End

Object GondorAragornMP
RemoveModule ModuleTag_AthelasAutoAbility
RemoveModule ModuleTag_BladeOfPurityAutoAbility
RemoveModule ModuleTag_ElendilAutoAbility
RemoveModule ModuleTag_AotDAutoAbility
AddModule
	Behavior = AutoAbilityBehavior ModuleTag_AthelasAutoAbilityAC
		SpecialAbility	= SpecialAbility202AragornAthelas
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange	= 175
		StartsActive = Yes
		Query		= 1 NONE +HERO ALLIES
	End
	Behavior = AutoAbilityBehavior ModuleTag_BladeOfPurityAutoAbilityAC
		SpecialAbility				= SpecialAbilityAragornBladeMaster
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange				= 200
		StartsActive = Yes
		Query						= 15 ALL ENEMIES -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL
		Query						= 1 ANY ENEMIES +HERO +MONSTER 
	End
	Behavior = AutoAbilityBehavior ModuleTag_ElendilAutoAbilityAC
		SpecialAbility	= SpecialAbilityAragornElendil
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange	= 180
		StartsActive = Yes
		Query								= 30 ANY ENEMIES +INFANTRY +CAVALRY ;,; 45 ANY ENEMIES +INFANTRY +CAVALRY -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE
	End
	Behavior = AutoAbilityBehavior ModuleTag_AotDAutoAbilityAC
		SpecialAbility	= SuperweaponSpawnOathbreakers
		ForbiddenStatus = INSIDE_GARRISON
		MaxScanRange	= 300
		StartsActive = Yes
		Query		= 40 ANY ENEMIES +INFANTRY +CAVALRY -STRUCTURE -WALL_UPGRADE -WALL_HUB -WALL_SEGMENT -DEFENSIVE_WALL -FS_BASE_DEFENSE
	End
End
End

Object RohanHeroStatueNoLeadership
RemoveModule ModuleTag_05
Scale = 0.1
RadarPriority  = INVALID
AddModule
  Body         = ImmortalBody ModuleTag_051
    MaxHealth  = ROHAN_HEROSTATUE_MAXHEALTH
  End
	Behavior = PassiveAreaEffectBehavior ModuleTag_FeelGoodHero
		EffectRadius			= 99999
		PingDelay				= 2000
		ModifierName			= YourTimeIsOverModifier
		AllowFilter				= ANY +INFANTRY +CAVALRY +HERO -MONSTER -SIEGEENGINE -MACHINE -IMMOBILE -DOZER -STRUCTURE -BASE_FOUNDATION -HORDE -SHIP -DwarvenBattleWagon -RohanOathbreaker -RohanOathbreaker1 -RohanOathbreakersCavalry -RohanOathbreakerHorde -RohanOathbreakerHordeSmall -MordorRamCrew +MordorWorker -IsengardRamCrew -IsengardBeserker -DwarvenZerker -DwarvenZerkerHorde -NoldorWarrior -NoldorWarriorHorde -GondorKnightsofDol -GondorKnightsofDolHorde -WildBabyDrake -WildBabyDrakeHorde -MordorBlackRider -MordorBlackRiderHorde -IsengardFanatic -IsengardBerserkerHorde -IsengardExplosiveMine -IsengardDeployedExplosiveMine -WildSpiderling_Slaved -AngmarDireWolf_Slaved -IsengardWarg_Slaved
	End
End
End

Object RohanEdorasDoor
RemoveModule ModuleTag_02
AddModule
	Body                  = ActiveBody ModuleTag_02
		MaxHealth       = 10000.0
	End
End
End